source "https://rubygems.org"

gem "activerecord",           "~> 5.1"
gem "eventmachine",           "~> 1.2"
gem "rubocop",                "~> 0.51"
gem "rubocop-github",         "~> 0.5"
gem "pry-byebug",             "~> 3.5"
gem "factory_bot",            "~> 4.8"
gem "faker",                  "~> 1.8"
gem "random-word",            "~> 2.1"
gem "rspec",                  "~> 3.6"
gem "guard-rspec",            "~> 4.7"
gem "simplecov",              "~> 0.15"
gem "pg",                     "~> 0.21"
gem "standalone_migrations",  "~> 5.2"
gem "database_cleaner",       "~> 1.6"
gem "dotenv",                 "~> 2.2"
gem "colorize",               "~> 0.8"
