source "https://rubygems.org"

gem "activerecord"
gem "eventmachine",   "~>  1.2.5"
gem "rubocop",        "~> 0.51.0"
gem "rubocop-github", "~> 0.5"
gem "pry-byebug"
gem "factory_bot"
gem "faker"
gem "rspec",          "~> 3.0"
gem "guard-rspec",    "~> 4.7"
gem "simplecov",      "~> 0.15"
gem "pg"
gem "standalone_migrations", "~> 5.2.3"
gem "database_cleaner", "~> 1.6.1"
gem "dotenv"
gem "colorize"
